### ISSUE TITLE
come up with specification of errors (and warnings?) expected in this particular dataset

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-error-examples#2]
Should relate tightly to error codes in our BIDS table, and paths where it was detected for.

Could be saved in some .yaml file like .bids-errors.yaml

```yaml
---
- error_key: ECHO_TIME_MUST_DEFINE
  paths:
  - sub-01/func/sub-01_func.json
```

FWIW google doc with errors for bids https://docs.google.com/spreadsheets/d/181vtw2bt2nHcUgw__G_gFSkKGyuxOxUNr5wHrZXY_uI/edit?pli=1#gid=0
